apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: inventory-demo
  labels:
    app: frontend
    component: ui
    service: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    service.beta.openshift.io/serving-cert-secret-name: frontend-tls
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: frontend
    version: v1
  sessionAffinity: None