apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory-demo
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: inventory-demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ausbru87/openshift-servicemesh-inventory-demo.git
    targetRevision: HEAD
    path: manifests
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: inventory-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  # REMOVED - deployment replicas ignore (was causing phantom ReplicaSets)
  # NEW - Target ONLY virt-launcher pods by name pattern
  - group: ""
    kind: Pod
    name: virt-launcher-*
    jsonPointers:
    - /status
