apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory-demo
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: inventory-demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ausbru87/openshift-servicemesh-inventory-demo.git
    targetRevision: HEAD
    path: manifests
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: inventory-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  # KubeVirt VirtualMachine ignoreDifferences (recommended best practice)
  - group: kubevirt.io
    kind: VirtualMachine
    managedFieldsManagers:
    - kubevirt-virt-controller
    - kubemacpool
    - virt-controller
  - group: kubevirt.io
    kind: VirtualMachine
    jsonPointers:
    # Kubernetes-managed metadata
    - /metadata/finalizers
    - /metadata/generation
    - /metadata/resourceVersion
    - /metadata/uid
    - /metadata/creationTimestamp
    # KubeVirt-specific annotations
    - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration
    - /metadata/annotations/kubemacpool.io~1transaction-timestamp
    - /metadata/annotations/kubevirt.io~1latest-observed-api-version
    - /metadata/annotations/kubevirt.io~1storage-observed-api-version
    # Status field (managed by KubeVirt controllers)
    - /status
    # Spec fields that KubeVirt modifies
    - /spec/template/spec/architecture
    - /spec/template/spec/domain/devices/interfaces/0/macAddress
    - /spec/template/metadata/creationTimestamp
    - /spec/dataVolumeTemplates/0/metadata/creationTimestamp
    # Spec fields that OpenShift modifies
    - /spec/template/spec/nodeSelector