apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: inventory-demo
  labels:
    app: backend
    component: api
    service: backend
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    # Service Mesh annotations
    service.beta.openshift.io/serving-cert-secret-name: backend-tls
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: backend
    version: v1
  sessionAffinity: None