apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: inventory-demo
  labels:
    app: backend
    component: api
    version: v1
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        component: api
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      securityContext:
        runAsNonRoot: true
        # Remove explicit runAsUser and fsGroup - let OpenShift assign them
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: backend
        # GitHub Container Registry image - updated by GitHub Actions
        image: ghcr.io/ausbru87/openshift-servicemesh-inventory-demo/inventory-backend:48b430c
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: backend-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: SECRET_KEY
          value: "demo-secret-key-change-in-production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          # Remove explicit runAsUser - let OpenShift assign it
          seccompProfile:
            type: RuntimeDefault
      restartPolicy: Always
      dnsPolicy: ClusterFirst