apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: inventory-demo
  labels:
    app: backend
    component: api
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  # Flask configuration
  FLASK_ENV: "production"
  FLASK_DEBUG: "false"
  
  # Database configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "inventory"
  DB_USER: "postgres"
  
  # Service Mesh and legacy service configuration
  LEGACY_SERVICE_URL: "http://legacy-service:8080"
  USE_MOCK_VALIDATION: "false"
  
  # API configuration
  API_TITLE: "OpenShift Service Mesh Inventory API"
  API_VERSION: "1.0.0"
  API_DESCRIPTION: "Inventory management API demonstrating Service Mesh integration"
  
  # Pagination and performance
  DEFAULT_PAGE_SIZE: "20"
  MAX_PAGE_SIZE: "100"
  LEGACY_SERVICE_TIMEOUT: "10"
  
  # CORS configuration
  CORS_ORIGINS: "*"
  
  # Logging configuration
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Health check configuration
  HEALTH_CHECK_TIMEOUT: "5"