apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init
  namespace: inventory-demo
  labels:
    app: postgres-init
    component: database
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    metadata:
      labels:
        app: postgres-init
        component: database
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      restartPolicy: OnFailure
      containers:
      - name: postgres-init
        image: registry.redhat.io/rhel8/postgresql-13:latest
        command:
        - /bin/bash
        - -c
        - |
          echo "Starting database initialization..."
          
          # Wait for PostgreSQL to be ready
          until pg_isready -h postgres-service -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done
          
          echo "PostgreSQL is ready, creating database..."
          
          # Create database if it doesn't exist
          psql -h postgres-service -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'inventory'" | grep -q 1
          if [ $? -ne 0 ]; then
            echo "Creating inventory database..."
            psql -h postgres-service -U postgres -c "CREATE DATABASE inventory;"
            echo "Database created successfully"
          else
            echo "Database already exists"
          fi
          
          echo "Database initialization complete"
          
          # Shut down Istio sidecar to allow job completion
          echo "Shutting down Istio sidecar..."
          curl -fsI -X POST http://localhost:15000/quitquitquit && echo "Istio sidecar shutdown successful" || echo "Istio sidecar shutdown failed (may not be needed)"
          
          echo "Job completed"
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password