apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: inventory-demo
  labels:
    app: postgres
    component: database
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  POSTGRES_DB: "inventory"
  POSTGRES_USER: "postgres"
  # PostgreSQL configuration
  postgresql.conf: |
    # Basic PostgreSQL configuration for demo environment
    listen_addresses = '*'
    max_connections = 100
    shared_buffers = 128MB
    effective_cache_size = 256MB
    maintenance_work_mem = 64MB
    checkpoint_completion_target = 0.9
    wal_buffers = 16MB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    work_mem = 4MB
    min_wal_size = 1GB
    max_wal_size = 4GB
    
    # Logging configuration
    log_destination = 'stderr'
    logging_collector = on
    log_directory = 'log'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_statement = 'all'
    log_duration = on
    log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
    
    # Service Mesh compatibility
    max_prepared_transactions = 100