apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: inventory-demo
  labels:
    app: postgres
    component: database
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  # Base64 encoded values
  # username: postgres (cG9zdGdyZXM=)
  # password: postgres (cG9zdGdyZXM=)
  # For production, use stronger passwords and external secret management
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
  database: aW52ZW50b3J5