apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: inventory-demo
  labels:
    app: postgres
    component: database
    version: v1
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  strategy:
    type: Recreate  # Required for PVC
  selector:
    matchLabels:
      app: postgres
      version: v1
  template:
    metadata:
      labels:
        app: postgres
        component: database
        version: v1
      annotations:
        # Enable Istio sidecar injection for Service Mesh
        sidecar.istio.io/inject: "true"
        # PostgreSQL specific annotations
        prometheus.io/scrape: "false"
        prometheus.io/port: "5432"
    spec:
      securityContext:
        runAsNonRoot: false  # PostgreSQL container needs specific user setup
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: postgres
        image: registry.redhat.io/rhel8/postgresql-13:latest
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
        env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database
        - name: PGDATA
          value: /var/lib/pgsql/data/pgdata
        - name: POSTGRES_INITDB_ARGS
          value: "--auth-host=md5"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/pgsql/data
        - name: postgres-config
          mountPath: /opt/app-root/src/postgresql-cfg/postgresql.conf
          subPath: postgresql.conf
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - /usr/libexec/check-container
            - --live
          initialDelaySeconds: 120
          timeoutSeconds: 10
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /usr/libexec/check-container
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          # PostgreSQL needs to run as postgres user (999)
          runAsUser: 999
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: postgres-config
        configMap:
          name: postgres-config
      restartPolicy: Always
      dnsPolicy: ClusterFirst