# Update manifests/05-vm/vm-destination-rule.yaml
# Remove the TLS configuration since VMs don't have Istio sidecars
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: legacy-validator-dr
  namespace: inventory-demo
  labels:
    app: legacy-validator
    component: vm
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: "Replace=true,SkipDryRunOnMissingResource=true"
spec:
  host: legacy-service.inventory-demo.svc.cluster.local
  trafficPolicy:
    # Connection pooling for the legacy service
    connectionPool:
      tcp:
        maxConnections: 10
        connectTimeout: 10s
      http:
        http1MaxPendingRequests: 10
        maxRequestsPerConnection: 2
        consecutiveGatewayErrors: 3
        interval: 30s
        baseEjectionTime: 30s
    
    # Circuit breaker for resilience
    outlierDetection:
      consecutiveGatewayErrors: 3
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
      minHealthPercent: 50
    
    # Load balancer configuration
    loadBalancer:
      simple: LEAST_CONN
      
    # REMOVED: tls configuration since VM doesn't have Istio sidecar
  
  # Port-specific policies
  portLevelSettings:
  - port:
      number: 8080
    connectionPool:
      tcp:
        maxConnections: 5
        connectTimeout: 5s