apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: legacy-validator
  namespace: inventory-demo
  labels:
    app: legacy-validator
    component: vm
    version: v1
    # Service mesh labels
    service.istio.io/canonical-name: legacy-validator
    service.istio.io/canonical-revision: v1
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "Replace=true"
    # Ensure this VM is managed by ArgoCD
    argocd.argoproj.io/managed-by: "argocd"
    # Note: VMs don't get Istio sidecar injection automatically
    # We'll handle service mesh integration via WorkloadEntry
    kubevirt.io/vm: legacy-validator
    # Description for the VM
    openshift.io/description: "Legacy Fedora VM running item validation service"
    # Display name for the VM in OpenShift console
    openshift.io/display-name: "Legacy Validator VM"
    # This VM is part of the Service Mesh Inventory demo
    app.kubernetes.io/part-of: servicemesh-inventory
    # This VM is part of the inventory-demo namespace
    app.kubernetes.io/namespace: inventory-demo
    # This VM is part of the inventory-demo application
    app.kubernetes.io/application: inventory-demo
spec:
  # VM should be running
  running: true
  
  # VM Template
  template:
    metadata:
      labels:
        app: legacy-validator
        component: vm
        version: v1
        # Important: These labels help with service mesh integration
        kubevirt.io/vm: legacy-validator
        service.istio.io/canonical-name: legacy-validator
        service.istio.io/canonical-revision: v1
      annotations:
        # Note: VMs don't get Istio sidecar injection automatically
        # We'll handle service mesh integration via WorkloadEntry
        vm.kubevirt.io/os: "fedora39"
    spec:
      # VM should be scheduled and restart if it fails
      domain:
        # CPU and Memory configuration
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        memory:
          guest: 4Gi
        
        # Devices configuration
        devices:
          # Disk configuration
          disks:
          - name: rootdisk
            bootOrder: 1
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          
          # Network configuration
          interfaces:
          - name: default
            masquerade: {}
            
          # Enable serial console for troubleshooting
          rng: {}
        
        # Resource requirements
        resources:
          requests:
            memory: 4Gi
            cpu: "1"
          limits:
            memory: 4Gi
            cpu: "2"
            
        # Machine type for CentOS 7 (older)
        machine:
          type: q35 
          
      # Ensure VM gets scheduled
      nodeSelector: {}
      
      # Network configuration
      networks:
      - name: default
        pod: {}
        
      # Volume configuration
      volumes:
      - name: rootdisk
        dataVolume:
          name: legacy-validator-disk  # Must match dataVolumeTemplates name
      - name: cloudinitdisk
        cloudInitNoCloud:
          secretRef:
            name: legacy-validator-cloud-init
            
  # Data volume templates (this ensures the DataVolume is created with the VM)
  dataVolumeTemplates:
  - metadata:
      name: legacy-validator-disk  # This name must match the volume reference above
      labels:
        app: legacy-validator
        component: vm
    spec:
      source:
        http:
          # CenTOS 8 Stream image URL
          url: "https://download.fedoraproject.org/pub/fedora/linux/releases/39/Cloud/x86_64/images/Fedora-Cloud-Base-39-1.5.x86_64.qcow2"
      storage:
        resources:
          requests:
            storage: 40Gi
        accessModes:
          - ReadWriteMany  # Required for live migration
        storageClassName: nfs-nvme