apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: inventory-demo
  namespace: istio-system
  labels:
    app: frontend
    component: ui
spec:
  host: inventory-demo-inventory-demo.apps.oxcart.zambruhni.com
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  port:
    targetPort: http2
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
