# This Gateway resource configures the Istio Ingress Gateway to expose
# the frontend application to external traffic.
# It listens on HTTP port 80. The OpenShift Route will handle HTTPS termination.
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: inventory-demo-gateway
  namespace: inventory-demo # Gateway should be in the same namespace as the route/service
  labels:
    app: frontend
    component: ui
  annotations:
    argocd.argoproj.io/sync-wave: "5" # Sync after frontend deployment and service
spec:
  selector:
    istio: ingressgateway # This selects the default Istio Ingress Gateway pod
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP # Expecting plain HTTP from the OpenShift Router
    hosts:
    - "*" # Allow all hosts for now, or specify your route's hostname
  # Removed the HTTPS server block from the Gateway, as the OpenShift Route
  # is now configured to handle TLS termination (edge).
