apiVersion: v1
kind: Namespace
metadata:
  name: inventory-demo
  labels:
    name: inventory-demo
    app.kubernetes.io/name: inventory-demo
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: servicemesh-inventory
    # Service Mesh injection label
    istio-injection: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    openshift.io/display-name: "Service Mesh Inventory Demo"
    openshift.io/description: "Demonstration of Service Mesh integration with containers and VMs"